### PR TITLE
Make SglPPow package suggested for SmallGrp

### LINKED ISSUE #11: SglPPow package as suggested for SmallGrp?
Should SglPPow (https://www.gap-system.org/Packages/sglppow.html) be specified in PackageInfo.g as suggested package?

For example, if it is loaded, SglPPow works for some more orders.

### PR DESCRIPTION
**Pull request by alex-konovalov**
Closes #11.

Will also cause loading LiePRing(>=1.8), LieRing(>=2.2), which are suggested for SglPPow.

### CODE REVIEW

**Comment by markuspf** [comment]
So this will cause more packages to be loaded in GAP 4.9 by default (i.e. smallgrp is needed, and then sglppow is loaded if available which causes LieRing and LiePRing to load)?

**Comment by alex-konovalov** [comment]
@markuspf yes... I am uncertain about this. What are the reasons for SglPPow  to suggest LieRing and LiePRing - will look.

**Comment by alex-konovalov** [comment]
Unless there are strong reasons to load LieRing and LiePRing, i prefer to exclude them from suggestion in SglPPow but have SglPPow loaded by default. It comes as a big surprise to users that NrSmallGroups and AllSmallGroups etc returns more groups if SglPPow is loaded.

**Comment by alex-konovalov** [comment]
I've got some new insights. It occurs that LieRing and LiePRing should be needed for SglPPow rather than suggested. First, LiePRing needs LieRing. Second, dependencies between these packages are explained in https://www.gap-system.org/Manuals/pkg/sglppow/htm/CHAP001.htm.

Indeed, while this works fine
```
gap> LoadPackage("sglppow");
LieRing
 a package for working with Lie rings 
 by Serena Cicalo' and Willem de Graaf
----------------------------------------------------------------
Loading  LiePRing 1.8
by Michael Vaughan-Lee and Bettina Eick 
----------------------------------------------------------------
----------------------------------------------------------------
Loading SglPPow 2.0
by Michael Vaughan-Lee and Bettina Eick 
----------------------------------------------------------------
true
gap> NrSmallGroups(13^7);
1600573
gap> SmallGroup(13^7,1);
<pc group of size 62748517 with 7 generators>
```
loading the package with `LoadPackage("sglppow":OnlyNeeded);` results in this:
```
gap> SmallGroup(13^7,1);
Error, sorry, but groups of size p^7 are available for p<=11 only at /Users/alexk/GITREPS/gap/small/small11/smlgp11.g:84 called from
SMALL_GROUP_FUNCS[inforec.func]( size, i, inforec 
 ) at /Users/alexk/GITREPS/gap/small/small.gi:113 called from
<function "SmallGroup">( <arguments> )
 called from read-eval loop at *stdin*:4
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```

**Comment by alex-konovalov** [comment]
Closing this, but important to mention SglPPow in the README and documentation - left a reminder in #22

**Pull request closed without merging**
